# Dockerfile.Sim
FROM python:3.14-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libexpat1 \
    libz-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir osmium networkx

CMD ["tail", "-f", "/dev/null"]