FROM ubuntu:26.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake gdb ninja-build git clang libsimdjson-dev \
    && rm -rf /var/lib/apt/lists/*

ENV CC=clang-21 CXX=clang++-21
WORKDIR /workspace/proj