services:
  rts:
    build:
      context: .
      dockerfile: Dockerfile.RTS
    volumes:
      - ./proj:/workspace/proj
    working_dir: /workspace/proj
    depends_on:
      - sim
    networks:
      - app-net

  sim:
    build:
      context: .
      dockerfile: Dockerfile.Sim
    volumes:
      - ./proj/simScript:/app
    working_dir: /app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
